name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    services:
      docker:
        image: docker:24.0.7-dind
        options: --privileged
        ports:
          - 2375:2375

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Enable Docker for Testcontainers
        run: |
          sudo systemctl start docker
          docker --version

      - name: Run Tests with Testcontainers
        run: |
          cd wedding-planner-backend
          export TESTCONTAINERS_RYUK_DISABLED=true
          export DOCKER_HOST=tcp://localhost:2375
          ./gradlew test

      - name: Build with Gradle Wrapper
        run: cd wedding-planner-backend && ./gradlew build

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
        with:
          build-root-directory: wedding-planner-backend
